name: CDK COC BOT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
      
    - name: Install pip and test tools
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt
        pip install pytest
        pip install flake8

    - name: Install dev env and test
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: cdk diff
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'diff'
        actions_comment: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        DEVELOPER_EMAIL_COC_API:  ${{ secrets.DEVELOPER_EMAIL_COC_API }}
        DEVELOPER_PASSWORD_COC_API:  ${{ secrets.DEVELOPER_PASSWORD_COC_API }}
        DISCORD_BOT_TOKEN:  ${{ secrets.DISCORD_BOT_TOKEN }}
        
    - name: cdk deploy
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'deploy'
        cdk_stack: 'stack1'
        cdk_args: '--require-approval never'
        actions_comment: false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION:  ${{ secrets.AWS_DEFAULT_REGION }}
        DEVELOPER_EMAIL_COC_API:  ${{ secrets.DEVELOPER_EMAIL_COC_API }}
        DEVELOPER_PASSWORD_COC_API:  ${{ secrets.DEVELOPER_PASSWORD_COC_API }}
        DISCORD_BOT_TOKEN:  ${{ secrets.DISCORD_BOT_TOKEN }}
        
    - name: cdk synth
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'synth'
        cdk_version: '1.16.2'
        working_dir: '.'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION:  ${{ secrets.AWS_DEFAULT_REGION }}
        DEVELOPER_EMAIL_COC_API:  ${{ secrets.DEVELOPER_EMAIL_COC_API }}
        DEVELOPER_PASSWORD_COC_API:  ${{ secrets.DEVELOPER_PASSWORD_COC_API }}
        DISCORD_BOT_TOKEN:  ${{ secrets.DISCORD_BOT_TOKEN }}
